---
- name: Copy core scripts
  copy:
    src: core/
    dest: /usr/local/bin/
    mode: '0755'

- name: Deploy aliases
  template:
    src: backup_core/alias.sh.j2
    dest: "{{ paths.core }}/alias.sh"

- name: Deploy motd
  template:
    src: backup_core/moth.sh.j2
    dest: "{{ paths.core }}/moth.sh"
    mode: '0755'

- name: Deploy start.sh
  template:
    src: backup_core/start.sh.j2
    dest: "{{ paths.core }}/start.sh"
    mode: '0755'