- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ paths.base }}"
    - "{{ paths.postgres }}"
   # - "{{ paths.etcd }}"
    - "{{ paths.configs }}"
    - "{{ paths.volumes }}"
    - "{{ paths.logs_pg }}"
    - "{{ paths.core }}"
    - "{{ paths.pgbackrest }}"