---
- import_tasks: dirs.yml
- import_tasks: core.yml
#- import_tasks: pgbackrest.yml
- import_tasks: systemd.yml
- import_tasks: timers.yml
#- import_tasks: restore.yml
#- import_tasks: del_old_backup.yml
